---
name: 🐛 Bug Report
about: Créer un rapport de bug pour nous aider à améliorer le projet
title: '[BUG] '
labels: ['bug', 'needs-triage']
assignees: ''
---

## 🐛 Description du Bug
Une description claire et concise du problème rencontré.

## 🔄 Étapes pour Reproduire
Étapes pour reproduire le comportement :
1. Aller à '...'
2. Cliquer sur '....'
3. Défiler jusqu'à '....'
4. Voir l'erreur

## ✅ Comportement Attendu
Une description claire et concise de ce qui devrait se passer.

## 📸 Captures d'Écran
Si applicable, ajoutez des captures d'écran pour aider à expliquer votre problème.

## 💻 Environnement
- **OS** : [ex. macOS 14.5, Windows 11, Ubuntu 22.04]
- **Node.js** : [ex. 18.17.0]
- **npm** : [ex. 9.6.7]
- **PHP** : [ex. 8.3.0]
- **Composer** : [ex. 2.6.0]
- **Navigateur** : [ex. Chrome 115, Firefox 116]

## 📋 Logs d'Erreur
```
Collez ici les logs d'erreur pertinents
```

## 🔧 Configuration
- **Template utilisé** : [Modern SAAS / E-commerce / Portfolio]
- **Couleurs personnalisées** : [Oui/Non]
- **Panel admin activé** : [Oui/Non]

## 📝 Contexte Additionnel
Ajoutez tout autre contexte sur le problème ici.

## ✅ Checklist
- [ ] J'ai vérifié que ce bug n'a pas déjà été signalé
- [ ] J'ai testé sur la dernière version
- [ ] J'ai inclus toutes les informations nécessaires
- [ ] J'ai testé les étapes de reproduction
